// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"iframe","status":true,"description":"Shows/hides a separate webpage using an iframe.","parameters":{"debugMode":"true"}}
];
